/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradeProfessionalsRouteImport } from './routes/trade-professionals'
import { Route as HomeownersRouteImport } from './routes/homeowners'
import { Route as HeritageListedBuildings2RouteImport } from './routes/heritage-listed-buildings-2'
import { Route as HeritageListedBuildingsRouteImport } from './routes/heritage-listed-buildings'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as CareAdviceRouteImport } from './routes/care-advice'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VacuumWindowsIndexRouteImport } from './routes/vacuum-windows/index'
import { Route as VacuumDoorsIndexRouteImport } from './routes/vacuum-doors/index'
import { Route as InspirationIndexRouteImport } from './routes/inspiration/index'
import { Route as VacuumWindowsTiltAndTurnRouteImport } from './routes/vacuum-windows/tilt-and-turn'
import { Route as VacuumWindowsSlidingSashRouteImport } from './routes/vacuum-windows/sliding-sash'
import { Route as VacuumWindowsMouldingsBarsRouteImport } from './routes/vacuum-windows/mouldings-bars'
import { Route as VacuumWindowsLippedCasementRouteImport } from './routes/vacuum-windows/lipped-casement'
import { Route as VacuumWindowsIronmongeryRouteImport } from './routes/vacuum-windows/ironmongery'
import { Route as VacuumWindowsFlushCasementRouteImport } from './routes/vacuum-windows/flush-casement'
import { Route as VacuumWindowsFinishesRouteImport } from './routes/vacuum-windows/finishes'
import { Route as VacuumWindowsAcousticRouteImport } from './routes/vacuum-windows/acoustic'
import { Route as VacuumDoorsSlidingPatioRouteImport } from './routes/vacuum-doors/sliding-patio'
import { Route as VacuumDoorsMouldingsBarsRouteImport } from './routes/vacuum-doors/mouldings-bars'
import { Route as VacuumDoorsIronmongeryRouteImport } from './routes/vacuum-doors/ironmongery'
import { Route as VacuumDoorsFrenchRouteImport } from './routes/vacuum-doors/french'
import { Route as VacuumDoorsFinishesRouteImport } from './routes/vacuum-doors/finishes'
import { Route as VacuumDoorsEntranceRouteImport } from './routes/vacuum-doors/entrance'
import { Route as VacuumDoorsBiFoldRouteImport } from './routes/vacuum-doors/bi-fold'
import { Route as VacuumDoorsAcousticRouteImport } from './routes/vacuum-doors/acoustic'
import { Route as InspirationGalleryRouteImport } from './routes/inspiration/gallery'
import { Route as InspirationCaseStudiesRouteImport } from './routes/inspiration/case-studies'
import { Route as InspirationBlogRouteImport } from './routes/inspiration/blog'

const TradeProfessionalsRoute = TradeProfessionalsRouteImport.update({
  id: '/trade-professionals',
  path: '/trade-professionals',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeownersRoute = HomeownersRouteImport.update({
  id: '/homeowners',
  path: '/homeowners',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageListedBuildings2Route =
  HeritageListedBuildings2RouteImport.update({
    id: '/heritage-listed-buildings-2',
    path: '/heritage-listed-buildings-2',
    getParentRoute: () => rootRouteImport,
  } as any)
const HeritageListedBuildingsRoute = HeritageListedBuildingsRouteImport.update({
  id: '/heritage-listed-buildings',
  path: '/heritage-listed-buildings',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CareAdviceRoute = CareAdviceRouteImport.update({
  id: '/care-advice',
  path: '/care-advice',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VacuumWindowsIndexRoute = VacuumWindowsIndexRouteImport.update({
  id: '/vacuum-windows/',
  path: '/vacuum-windows/',
  getParentRoute: () => rootRouteImport,
} as any)
const VacuumDoorsIndexRoute = VacuumDoorsIndexRouteImport.update({
  id: '/vacuum-doors/',
  path: '/vacuum-doors/',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationIndexRoute = InspirationIndexRouteImport.update({
  id: '/inspiration/',
  path: '/inspiration/',
  getParentRoute: () => rootRouteImport,
} as any)
const VacuumWindowsTiltAndTurnRoute =
  VacuumWindowsTiltAndTurnRouteImport.update({
    id: '/vacuum-windows/tilt-and-turn',
    path: '/vacuum-windows/tilt-and-turn',
    getParentRoute: () => rootRouteImport,
  } as any)
const VacuumWindowsSlidingSashRoute =
  VacuumWindowsSlidingSashRouteImport.update({
    id: '/vacuum-windows/sliding-sash',
    path: '/vacuum-windows/sliding-sash',
    getParentRoute: () => rootRouteImport,
  } as any)
const VacuumWindowsMouldingsBarsRoute =
  VacuumWindowsMouldingsBarsRouteImport.update({
    id: '/vacuum-windows/mouldings-bars',
    path: '/vacuum-windows/mouldings-bars',
    getParentRoute: () => rootRouteImport,
  } as any)
const VacuumWindowsLippedCasementRoute =
  VacuumWindowsLippedCasementRouteImport.update({
    id: '/vacuum-windows/lipped-casement',
    path: '/vacuum-windows/lipped-casement',
    getParentRoute: () => rootRouteImport,
  } as any)
const VacuumWindowsIronmongeryRoute =
  VacuumWindowsIronmongeryRouteImport.update({
    id: '/vacuum-windows/ironmongery',
    path: '/vacuum-windows/ironmongery',
    getParentRoute: () => rootRouteImport,
  } as any)
const VacuumWindowsFlushCasementRoute =
  VacuumWindowsFlushCasementRouteImport.update({
    id: '/vacuum-windows/flush-casement',
    path: '/vacuum-windows/flush-casement',
    getParentRoute: () => rootRouteImport,
  } as any)
const VacuumWindowsFinishesRoute = VacuumWindowsFinishesRouteImport.update({
  id: '/vacuum-windows/finishes',
  path: '/vacuum-windows/finishes',
  getParentRoute: () => rootRouteImport,
} as any)
const VacuumWindowsAcousticRoute = VacuumWindowsAcousticRouteImport.update({
  id: '/vacuum-windows/acoustic',
  path: '/vacuum-windows/acoustic',
  getParentRoute: () => rootRouteImport,
} as any)
const VacuumDoorsSlidingPatioRoute = VacuumDoorsSlidingPatioRouteImport.update({
  id: '/vacuum-doors/sliding-patio',
  path: '/vacuum-doors/sliding-patio',
  getParentRoute: () => rootRouteImport,
} as any)
const VacuumDoorsMouldingsBarsRoute =
  VacuumDoorsMouldingsBarsRouteImport.update({
    id: '/vacuum-doors/mouldings-bars',
    path: '/vacuum-doors/mouldings-bars',
    getParentRoute: () => rootRouteImport,
  } as any)
const VacuumDoorsIronmongeryRoute = VacuumDoorsIronmongeryRouteImport.update({
  id: '/vacuum-doors/ironmongery',
  path: '/vacuum-doors/ironmongery',
  getParentRoute: () => rootRouteImport,
} as any)
const VacuumDoorsFrenchRoute = VacuumDoorsFrenchRouteImport.update({
  id: '/vacuum-doors/french',
  path: '/vacuum-doors/french',
  getParentRoute: () => rootRouteImport,
} as any)
const VacuumDoorsFinishesRoute = VacuumDoorsFinishesRouteImport.update({
  id: '/vacuum-doors/finishes',
  path: '/vacuum-doors/finishes',
  getParentRoute: () => rootRouteImport,
} as any)
const VacuumDoorsEntranceRoute = VacuumDoorsEntranceRouteImport.update({
  id: '/vacuum-doors/entrance',
  path: '/vacuum-doors/entrance',
  getParentRoute: () => rootRouteImport,
} as any)
const VacuumDoorsBiFoldRoute = VacuumDoorsBiFoldRouteImport.update({
  id: '/vacuum-doors/bi-fold',
  path: '/vacuum-doors/bi-fold',
  getParentRoute: () => rootRouteImport,
} as any)
const VacuumDoorsAcousticRoute = VacuumDoorsAcousticRouteImport.update({
  id: '/vacuum-doors/acoustic',
  path: '/vacuum-doors/acoustic',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationGalleryRoute = InspirationGalleryRouteImport.update({
  id: '/inspiration/gallery',
  path: '/inspiration/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationCaseStudiesRoute = InspirationCaseStudiesRouteImport.update({
  id: '/inspiration/case-studies',
  path: '/inspiration/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationBlogRoute = InspirationBlogRouteImport.update({
  id: '/inspiration/blog',
  path: '/inspiration/blog',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/care-advice': typeof CareAdviceRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/heritage-listed-buildings': typeof HeritageListedBuildingsRoute
  '/heritage-listed-buildings-2': typeof HeritageListedBuildings2Route
  '/homeowners': typeof HomeownersRoute
  '/trade-professionals': typeof TradeProfessionalsRoute
  '/inspiration/blog': typeof InspirationBlogRoute
  '/inspiration/case-studies': typeof InspirationCaseStudiesRoute
  '/inspiration/gallery': typeof InspirationGalleryRoute
  '/vacuum-doors/acoustic': typeof VacuumDoorsAcousticRoute
  '/vacuum-doors/bi-fold': typeof VacuumDoorsBiFoldRoute
  '/vacuum-doors/entrance': typeof VacuumDoorsEntranceRoute
  '/vacuum-doors/finishes': typeof VacuumDoorsFinishesRoute
  '/vacuum-doors/french': typeof VacuumDoorsFrenchRoute
  '/vacuum-doors/ironmongery': typeof VacuumDoorsIronmongeryRoute
  '/vacuum-doors/mouldings-bars': typeof VacuumDoorsMouldingsBarsRoute
  '/vacuum-doors/sliding-patio': typeof VacuumDoorsSlidingPatioRoute
  '/vacuum-windows/acoustic': typeof VacuumWindowsAcousticRoute
  '/vacuum-windows/finishes': typeof VacuumWindowsFinishesRoute
  '/vacuum-windows/flush-casement': typeof VacuumWindowsFlushCasementRoute
  '/vacuum-windows/ironmongery': typeof VacuumWindowsIronmongeryRoute
  '/vacuum-windows/lipped-casement': typeof VacuumWindowsLippedCasementRoute
  '/vacuum-windows/mouldings-bars': typeof VacuumWindowsMouldingsBarsRoute
  '/vacuum-windows/sliding-sash': typeof VacuumWindowsSlidingSashRoute
  '/vacuum-windows/tilt-and-turn': typeof VacuumWindowsTiltAndTurnRoute
  '/inspiration/': typeof InspirationIndexRoute
  '/vacuum-doors/': typeof VacuumDoorsIndexRoute
  '/vacuum-windows/': typeof VacuumWindowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/care-advice': typeof CareAdviceRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/heritage-listed-buildings': typeof HeritageListedBuildingsRoute
  '/heritage-listed-buildings-2': typeof HeritageListedBuildings2Route
  '/homeowners': typeof HomeownersRoute
  '/trade-professionals': typeof TradeProfessionalsRoute
  '/inspiration/blog': typeof InspirationBlogRoute
  '/inspiration/case-studies': typeof InspirationCaseStudiesRoute
  '/inspiration/gallery': typeof InspirationGalleryRoute
  '/vacuum-doors/acoustic': typeof VacuumDoorsAcousticRoute
  '/vacuum-doors/bi-fold': typeof VacuumDoorsBiFoldRoute
  '/vacuum-doors/entrance': typeof VacuumDoorsEntranceRoute
  '/vacuum-doors/finishes': typeof VacuumDoorsFinishesRoute
  '/vacuum-doors/french': typeof VacuumDoorsFrenchRoute
  '/vacuum-doors/ironmongery': typeof VacuumDoorsIronmongeryRoute
  '/vacuum-doors/mouldings-bars': typeof VacuumDoorsMouldingsBarsRoute
  '/vacuum-doors/sliding-patio': typeof VacuumDoorsSlidingPatioRoute
  '/vacuum-windows/acoustic': typeof VacuumWindowsAcousticRoute
  '/vacuum-windows/finishes': typeof VacuumWindowsFinishesRoute
  '/vacuum-windows/flush-casement': typeof VacuumWindowsFlushCasementRoute
  '/vacuum-windows/ironmongery': typeof VacuumWindowsIronmongeryRoute
  '/vacuum-windows/lipped-casement': typeof VacuumWindowsLippedCasementRoute
  '/vacuum-windows/mouldings-bars': typeof VacuumWindowsMouldingsBarsRoute
  '/vacuum-windows/sliding-sash': typeof VacuumWindowsSlidingSashRoute
  '/vacuum-windows/tilt-and-turn': typeof VacuumWindowsTiltAndTurnRoute
  '/inspiration': typeof InspirationIndexRoute
  '/vacuum-doors': typeof VacuumDoorsIndexRoute
  '/vacuum-windows': typeof VacuumWindowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/care-advice': typeof CareAdviceRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/heritage-listed-buildings': typeof HeritageListedBuildingsRoute
  '/heritage-listed-buildings-2': typeof HeritageListedBuildings2Route
  '/homeowners': typeof HomeownersRoute
  '/trade-professionals': typeof TradeProfessionalsRoute
  '/inspiration/blog': typeof InspirationBlogRoute
  '/inspiration/case-studies': typeof InspirationCaseStudiesRoute
  '/inspiration/gallery': typeof InspirationGalleryRoute
  '/vacuum-doors/acoustic': typeof VacuumDoorsAcousticRoute
  '/vacuum-doors/bi-fold': typeof VacuumDoorsBiFoldRoute
  '/vacuum-doors/entrance': typeof VacuumDoorsEntranceRoute
  '/vacuum-doors/finishes': typeof VacuumDoorsFinishesRoute
  '/vacuum-doors/french': typeof VacuumDoorsFrenchRoute
  '/vacuum-doors/ironmongery': typeof VacuumDoorsIronmongeryRoute
  '/vacuum-doors/mouldings-bars': typeof VacuumDoorsMouldingsBarsRoute
  '/vacuum-doors/sliding-patio': typeof VacuumDoorsSlidingPatioRoute
  '/vacuum-windows/acoustic': typeof VacuumWindowsAcousticRoute
  '/vacuum-windows/finishes': typeof VacuumWindowsFinishesRoute
  '/vacuum-windows/flush-casement': typeof VacuumWindowsFlushCasementRoute
  '/vacuum-windows/ironmongery': typeof VacuumWindowsIronmongeryRoute
  '/vacuum-windows/lipped-casement': typeof VacuumWindowsLippedCasementRoute
  '/vacuum-windows/mouldings-bars': typeof VacuumWindowsMouldingsBarsRoute
  '/vacuum-windows/sliding-sash': typeof VacuumWindowsSlidingSashRoute
  '/vacuum-windows/tilt-and-turn': typeof VacuumWindowsTiltAndTurnRoute
  '/inspiration/': typeof InspirationIndexRoute
  '/vacuum-doors/': typeof VacuumDoorsIndexRoute
  '/vacuum-windows/': typeof VacuumWindowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/care-advice'
    | '/certifications'
    | '/contact'
    | '/heritage-listed-buildings'
    | '/heritage-listed-buildings-2'
    | '/homeowners'
    | '/trade-professionals'
    | '/inspiration/blog'
    | '/inspiration/case-studies'
    | '/inspiration/gallery'
    | '/vacuum-doors/acoustic'
    | '/vacuum-doors/bi-fold'
    | '/vacuum-doors/entrance'
    | '/vacuum-doors/finishes'
    | '/vacuum-doors/french'
    | '/vacuum-doors/ironmongery'
    | '/vacuum-doors/mouldings-bars'
    | '/vacuum-doors/sliding-patio'
    | '/vacuum-windows/acoustic'
    | '/vacuum-windows/finishes'
    | '/vacuum-windows/flush-casement'
    | '/vacuum-windows/ironmongery'
    | '/vacuum-windows/lipped-casement'
    | '/vacuum-windows/mouldings-bars'
    | '/vacuum-windows/sliding-sash'
    | '/vacuum-windows/tilt-and-turn'
    | '/inspiration/'
    | '/vacuum-doors/'
    | '/vacuum-windows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/care-advice'
    | '/certifications'
    | '/contact'
    | '/heritage-listed-buildings'
    | '/heritage-listed-buildings-2'
    | '/homeowners'
    | '/trade-professionals'
    | '/inspiration/blog'
    | '/inspiration/case-studies'
    | '/inspiration/gallery'
    | '/vacuum-doors/acoustic'
    | '/vacuum-doors/bi-fold'
    | '/vacuum-doors/entrance'
    | '/vacuum-doors/finishes'
    | '/vacuum-doors/french'
    | '/vacuum-doors/ironmongery'
    | '/vacuum-doors/mouldings-bars'
    | '/vacuum-doors/sliding-patio'
    | '/vacuum-windows/acoustic'
    | '/vacuum-windows/finishes'
    | '/vacuum-windows/flush-casement'
    | '/vacuum-windows/ironmongery'
    | '/vacuum-windows/lipped-casement'
    | '/vacuum-windows/mouldings-bars'
    | '/vacuum-windows/sliding-sash'
    | '/vacuum-windows/tilt-and-turn'
    | '/inspiration'
    | '/vacuum-doors'
    | '/vacuum-windows'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/care-advice'
    | '/certifications'
    | '/contact'
    | '/heritage-listed-buildings'
    | '/heritage-listed-buildings-2'
    | '/homeowners'
    | '/trade-professionals'
    | '/inspiration/blog'
    | '/inspiration/case-studies'
    | '/inspiration/gallery'
    | '/vacuum-doors/acoustic'
    | '/vacuum-doors/bi-fold'
    | '/vacuum-doors/entrance'
    | '/vacuum-doors/finishes'
    | '/vacuum-doors/french'
    | '/vacuum-doors/ironmongery'
    | '/vacuum-doors/mouldings-bars'
    | '/vacuum-doors/sliding-patio'
    | '/vacuum-windows/acoustic'
    | '/vacuum-windows/finishes'
    | '/vacuum-windows/flush-casement'
    | '/vacuum-windows/ironmongery'
    | '/vacuum-windows/lipped-casement'
    | '/vacuum-windows/mouldings-bars'
    | '/vacuum-windows/sliding-sash'
    | '/vacuum-windows/tilt-and-turn'
    | '/inspiration/'
    | '/vacuum-doors/'
    | '/vacuum-windows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareAdviceRoute: typeof CareAdviceRoute
  CertificationsRoute: typeof CertificationsRoute
  ContactRoute: typeof ContactRoute
  HeritageListedBuildingsRoute: typeof HeritageListedBuildingsRoute
  HeritageListedBuildings2Route: typeof HeritageListedBuildings2Route
  HomeownersRoute: typeof HomeownersRoute
  TradeProfessionalsRoute: typeof TradeProfessionalsRoute
  InspirationBlogRoute: typeof InspirationBlogRoute
  InspirationCaseStudiesRoute: typeof InspirationCaseStudiesRoute
  InspirationGalleryRoute: typeof InspirationGalleryRoute
  VacuumDoorsAcousticRoute: typeof VacuumDoorsAcousticRoute
  VacuumDoorsBiFoldRoute: typeof VacuumDoorsBiFoldRoute
  VacuumDoorsEntranceRoute: typeof VacuumDoorsEntranceRoute
  VacuumDoorsFinishesRoute: typeof VacuumDoorsFinishesRoute
  VacuumDoorsFrenchRoute: typeof VacuumDoorsFrenchRoute
  VacuumDoorsIronmongeryRoute: typeof VacuumDoorsIronmongeryRoute
  VacuumDoorsMouldingsBarsRoute: typeof VacuumDoorsMouldingsBarsRoute
  VacuumDoorsSlidingPatioRoute: typeof VacuumDoorsSlidingPatioRoute
  VacuumWindowsAcousticRoute: typeof VacuumWindowsAcousticRoute
  VacuumWindowsFinishesRoute: typeof VacuumWindowsFinishesRoute
  VacuumWindowsFlushCasementRoute: typeof VacuumWindowsFlushCasementRoute
  VacuumWindowsIronmongeryRoute: typeof VacuumWindowsIronmongeryRoute
  VacuumWindowsLippedCasementRoute: typeof VacuumWindowsLippedCasementRoute
  VacuumWindowsMouldingsBarsRoute: typeof VacuumWindowsMouldingsBarsRoute
  VacuumWindowsSlidingSashRoute: typeof VacuumWindowsSlidingSashRoute
  VacuumWindowsTiltAndTurnRoute: typeof VacuumWindowsTiltAndTurnRoute
  InspirationIndexRoute: typeof InspirationIndexRoute
  VacuumDoorsIndexRoute: typeof VacuumDoorsIndexRoute
  VacuumWindowsIndexRoute: typeof VacuumWindowsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trade-professionals': {
      id: '/trade-professionals'
      path: '/trade-professionals'
      fullPath: '/trade-professionals'
      preLoaderRoute: typeof TradeProfessionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homeowners': {
      id: '/homeowners'
      path: '/homeowners'
      fullPath: '/homeowners'
      preLoaderRoute: typeof HomeownersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage-listed-buildings-2': {
      id: '/heritage-listed-buildings-2'
      path: '/heritage-listed-buildings-2'
      fullPath: '/heritage-listed-buildings-2'
      preLoaderRoute: typeof HeritageListedBuildings2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage-listed-buildings': {
      id: '/heritage-listed-buildings'
      path: '/heritage-listed-buildings'
      fullPath: '/heritage-listed-buildings'
      preLoaderRoute: typeof HeritageListedBuildingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-advice': {
      id: '/care-advice'
      path: '/care-advice'
      fullPath: '/care-advice'
      preLoaderRoute: typeof CareAdviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacuum-windows/': {
      id: '/vacuum-windows/'
      path: '/vacuum-windows'
      fullPath: '/vacuum-windows/'
      preLoaderRoute: typeof VacuumWindowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacuum-doors/': {
      id: '/vacuum-doors/'
      path: '/vacuum-doors'
      fullPath: '/vacuum-doors/'
      preLoaderRoute: typeof VacuumDoorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspiration/': {
      id: '/inspiration/'
      path: '/inspiration'
      fullPath: '/inspiration/'
      preLoaderRoute: typeof InspirationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacuum-windows/tilt-and-turn': {
      id: '/vacuum-windows/tilt-and-turn'
      path: '/vacuum-windows/tilt-and-turn'
      fullPath: '/vacuum-windows/tilt-and-turn'
      preLoaderRoute: typeof VacuumWindowsTiltAndTurnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacuum-windows/sliding-sash': {
      id: '/vacuum-windows/sliding-sash'
      path: '/vacuum-windows/sliding-sash'
      fullPath: '/vacuum-windows/sliding-sash'
      preLoaderRoute: typeof VacuumWindowsSlidingSashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacuum-windows/mouldings-bars': {
      id: '/vacuum-windows/mouldings-bars'
      path: '/vacuum-windows/mouldings-bars'
      fullPath: '/vacuum-windows/mouldings-bars'
      preLoaderRoute: typeof VacuumWindowsMouldingsBarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacuum-windows/lipped-casement': {
      id: '/vacuum-windows/lipped-casement'
      path: '/vacuum-windows/lipped-casement'
      fullPath: '/vacuum-windows/lipped-casement'
      preLoaderRoute: typeof VacuumWindowsLippedCasementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacuum-windows/ironmongery': {
      id: '/vacuum-windows/ironmongery'
      path: '/vacuum-windows/ironmongery'
      fullPath: '/vacuum-windows/ironmongery'
      preLoaderRoute: typeof VacuumWindowsIronmongeryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacuum-windows/flush-casement': {
      id: '/vacuum-windows/flush-casement'
      path: '/vacuum-windows/flush-casement'
      fullPath: '/vacuum-windows/flush-casement'
      preLoaderRoute: typeof VacuumWindowsFlushCasementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacuum-windows/finishes': {
      id: '/vacuum-windows/finishes'
      path: '/vacuum-windows/finishes'
      fullPath: '/vacuum-windows/finishes'
      preLoaderRoute: typeof VacuumWindowsFinishesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacuum-windows/acoustic': {
      id: '/vacuum-windows/acoustic'
      path: '/vacuum-windows/acoustic'
      fullPath: '/vacuum-windows/acoustic'
      preLoaderRoute: typeof VacuumWindowsAcousticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacuum-doors/sliding-patio': {
      id: '/vacuum-doors/sliding-patio'
      path: '/vacuum-doors/sliding-patio'
      fullPath: '/vacuum-doors/sliding-patio'
      preLoaderRoute: typeof VacuumDoorsSlidingPatioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacuum-doors/mouldings-bars': {
      id: '/vacuum-doors/mouldings-bars'
      path: '/vacuum-doors/mouldings-bars'
      fullPath: '/vacuum-doors/mouldings-bars'
      preLoaderRoute: typeof VacuumDoorsMouldingsBarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacuum-doors/ironmongery': {
      id: '/vacuum-doors/ironmongery'
      path: '/vacuum-doors/ironmongery'
      fullPath: '/vacuum-doors/ironmongery'
      preLoaderRoute: typeof VacuumDoorsIronmongeryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacuum-doors/french': {
      id: '/vacuum-doors/french'
      path: '/vacuum-doors/french'
      fullPath: '/vacuum-doors/french'
      preLoaderRoute: typeof VacuumDoorsFrenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacuum-doors/finishes': {
      id: '/vacuum-doors/finishes'
      path: '/vacuum-doors/finishes'
      fullPath: '/vacuum-doors/finishes'
      preLoaderRoute: typeof VacuumDoorsFinishesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacuum-doors/entrance': {
      id: '/vacuum-doors/entrance'
      path: '/vacuum-doors/entrance'
      fullPath: '/vacuum-doors/entrance'
      preLoaderRoute: typeof VacuumDoorsEntranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacuum-doors/bi-fold': {
      id: '/vacuum-doors/bi-fold'
      path: '/vacuum-doors/bi-fold'
      fullPath: '/vacuum-doors/bi-fold'
      preLoaderRoute: typeof VacuumDoorsBiFoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacuum-doors/acoustic': {
      id: '/vacuum-doors/acoustic'
      path: '/vacuum-doors/acoustic'
      fullPath: '/vacuum-doors/acoustic'
      preLoaderRoute: typeof VacuumDoorsAcousticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspiration/gallery': {
      id: '/inspiration/gallery'
      path: '/inspiration/gallery'
      fullPath: '/inspiration/gallery'
      preLoaderRoute: typeof InspirationGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspiration/case-studies': {
      id: '/inspiration/case-studies'
      path: '/inspiration/case-studies'
      fullPath: '/inspiration/case-studies'
      preLoaderRoute: typeof InspirationCaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspiration/blog': {
      id: '/inspiration/blog'
      path: '/inspiration/blog'
      fullPath: '/inspiration/blog'
      preLoaderRoute: typeof InspirationBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareAdviceRoute: CareAdviceRoute,
  CertificationsRoute: CertificationsRoute,
  ContactRoute: ContactRoute,
  HeritageListedBuildingsRoute: HeritageListedBuildingsRoute,
  HeritageListedBuildings2Route: HeritageListedBuildings2Route,
  HomeownersRoute: HomeownersRoute,
  TradeProfessionalsRoute: TradeProfessionalsRoute,
  InspirationBlogRoute: InspirationBlogRoute,
  InspirationCaseStudiesRoute: InspirationCaseStudiesRoute,
  InspirationGalleryRoute: InspirationGalleryRoute,
  VacuumDoorsAcousticRoute: VacuumDoorsAcousticRoute,
  VacuumDoorsBiFoldRoute: VacuumDoorsBiFoldRoute,
  VacuumDoorsEntranceRoute: VacuumDoorsEntranceRoute,
  VacuumDoorsFinishesRoute: VacuumDoorsFinishesRoute,
  VacuumDoorsFrenchRoute: VacuumDoorsFrenchRoute,
  VacuumDoorsIronmongeryRoute: VacuumDoorsIronmongeryRoute,
  VacuumDoorsMouldingsBarsRoute: VacuumDoorsMouldingsBarsRoute,
  VacuumDoorsSlidingPatioRoute: VacuumDoorsSlidingPatioRoute,
  VacuumWindowsAcousticRoute: VacuumWindowsAcousticRoute,
  VacuumWindowsFinishesRoute: VacuumWindowsFinishesRoute,
  VacuumWindowsFlushCasementRoute: VacuumWindowsFlushCasementRoute,
  VacuumWindowsIronmongeryRoute: VacuumWindowsIronmongeryRoute,
  VacuumWindowsLippedCasementRoute: VacuumWindowsLippedCasementRoute,
  VacuumWindowsMouldingsBarsRoute: VacuumWindowsMouldingsBarsRoute,
  VacuumWindowsSlidingSashRoute: VacuumWindowsSlidingSashRoute,
  VacuumWindowsTiltAndTurnRoute: VacuumWindowsTiltAndTurnRoute,
  InspirationIndexRoute: InspirationIndexRoute,
  VacuumDoorsIndexRoute: VacuumDoorsIndexRoute,
  VacuumWindowsIndexRoute: VacuumWindowsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
