/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VacuumGlazingRouteImport } from './routes/vacuum-glazing'
import { Route as SecondaryGlazingRouteImport } from './routes/secondary-glazing'
import { Route as SashWindowsRouteImport } from './routes/sash-windows'
import { Route as ManagingAgentsRouteImport } from './routes/managing-agents'
import { Route as InteriorDesignersRouteImport } from './routes/interior-designers'
import { Route as HomeownersRouteImport } from './routes/homeowners'
import { Route as DraughtproofingRouteImport } from './routes/draughtproofing'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as CasementWindowsRouteImport } from './routes/casement-windows'
import { Route as ArchitectsRouteImport } from './routes/architects'
import { Route as IndexRouteImport } from './routes/index'

const VacuumGlazingRoute = VacuumGlazingRouteImport.update({
  id: '/vacuum-glazing',
  path: '/vacuum-glazing',
  getParentRoute: () => rootRouteImport,
} as any)
const SecondaryGlazingRoute = SecondaryGlazingRouteImport.update({
  id: '/secondary-glazing',
  path: '/secondary-glazing',
  getParentRoute: () => rootRouteImport,
} as any)
const SashWindowsRoute = SashWindowsRouteImport.update({
  id: '/sash-windows',
  path: '/sash-windows',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagingAgentsRoute = ManagingAgentsRouteImport.update({
  id: '/managing-agents',
  path: '/managing-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const InteriorDesignersRoute = InteriorDesignersRouteImport.update({
  id: '/interior-designers',
  path: '/interior-designers',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeownersRoute = HomeownersRouteImport.update({
  id: '/homeowners',
  path: '/homeowners',
  getParentRoute: () => rootRouteImport,
} as any)
const DraughtproofingRoute = DraughtproofingRouteImport.update({
  id: '/draughtproofing',
  path: '/draughtproofing',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const CasementWindowsRoute = CasementWindowsRouteImport.update({
  id: '/casement-windows',
  path: '/casement-windows',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectsRoute = ArchitectsRouteImport.update({
  id: '/architects',
  path: '/architects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architects': typeof ArchitectsRoute
  '/casement-windows': typeof CasementWindowsRoute
  '/developers': typeof DevelopersRoute
  '/draughtproofing': typeof DraughtproofingRoute
  '/homeowners': typeof HomeownersRoute
  '/interior-designers': typeof InteriorDesignersRoute
  '/managing-agents': typeof ManagingAgentsRoute
  '/sash-windows': typeof SashWindowsRoute
  '/secondary-glazing': typeof SecondaryGlazingRoute
  '/vacuum-glazing': typeof VacuumGlazingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architects': typeof ArchitectsRoute
  '/casement-windows': typeof CasementWindowsRoute
  '/developers': typeof DevelopersRoute
  '/draughtproofing': typeof DraughtproofingRoute
  '/homeowners': typeof HomeownersRoute
  '/interior-designers': typeof InteriorDesignersRoute
  '/managing-agents': typeof ManagingAgentsRoute
  '/sash-windows': typeof SashWindowsRoute
  '/secondary-glazing': typeof SecondaryGlazingRoute
  '/vacuum-glazing': typeof VacuumGlazingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architects': typeof ArchitectsRoute
  '/casement-windows': typeof CasementWindowsRoute
  '/developers': typeof DevelopersRoute
  '/draughtproofing': typeof DraughtproofingRoute
  '/homeowners': typeof HomeownersRoute
  '/interior-designers': typeof InteriorDesignersRoute
  '/managing-agents': typeof ManagingAgentsRoute
  '/sash-windows': typeof SashWindowsRoute
  '/secondary-glazing': typeof SecondaryGlazingRoute
  '/vacuum-glazing': typeof VacuumGlazingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architects'
    | '/casement-windows'
    | '/developers'
    | '/draughtproofing'
    | '/homeowners'
    | '/interior-designers'
    | '/managing-agents'
    | '/sash-windows'
    | '/secondary-glazing'
    | '/vacuum-glazing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architects'
    | '/casement-windows'
    | '/developers'
    | '/draughtproofing'
    | '/homeowners'
    | '/interior-designers'
    | '/managing-agents'
    | '/sash-windows'
    | '/secondary-glazing'
    | '/vacuum-glazing'
  id:
    | '__root__'
    | '/'
    | '/architects'
    | '/casement-windows'
    | '/developers'
    | '/draughtproofing'
    | '/homeowners'
    | '/interior-designers'
    | '/managing-agents'
    | '/sash-windows'
    | '/secondary-glazing'
    | '/vacuum-glazing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectsRoute: typeof ArchitectsRoute
  CasementWindowsRoute: typeof CasementWindowsRoute
  DevelopersRoute: typeof DevelopersRoute
  DraughtproofingRoute: typeof DraughtproofingRoute
  HomeownersRoute: typeof HomeownersRoute
  InteriorDesignersRoute: typeof InteriorDesignersRoute
  ManagingAgentsRoute: typeof ManagingAgentsRoute
  SashWindowsRoute: typeof SashWindowsRoute
  SecondaryGlazingRoute: typeof SecondaryGlazingRoute
  VacuumGlazingRoute: typeof VacuumGlazingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vacuum-glazing': {
      id: '/vacuum-glazing'
      path: '/vacuum-glazing'
      fullPath: '/vacuum-glazing'
      preLoaderRoute: typeof VacuumGlazingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secondary-glazing': {
      id: '/secondary-glazing'
      path: '/secondary-glazing'
      fullPath: '/secondary-glazing'
      preLoaderRoute: typeof SecondaryGlazingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sash-windows': {
      id: '/sash-windows'
      path: '/sash-windows'
      fullPath: '/sash-windows'
      preLoaderRoute: typeof SashWindowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/managing-agents': {
      id: '/managing-agents'
      path: '/managing-agents'
      fullPath: '/managing-agents'
      preLoaderRoute: typeof ManagingAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interior-designers': {
      id: '/interior-designers'
      path: '/interior-designers'
      fullPath: '/interior-designers'
      preLoaderRoute: typeof InteriorDesignersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homeowners': {
      id: '/homeowners'
      path: '/homeowners'
      fullPath: '/homeowners'
      preLoaderRoute: typeof HomeownersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draughtproofing': {
      id: '/draughtproofing'
      path: '/draughtproofing'
      fullPath: '/draughtproofing'
      preLoaderRoute: typeof DraughtproofingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casement-windows': {
      id: '/casement-windows'
      path: '/casement-windows'
      fullPath: '/casement-windows'
      preLoaderRoute: typeof CasementWindowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architects': {
      id: '/architects'
      path: '/architects'
      fullPath: '/architects'
      preLoaderRoute: typeof ArchitectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectsRoute: ArchitectsRoute,
  CasementWindowsRoute: CasementWindowsRoute,
  DevelopersRoute: DevelopersRoute,
  DraughtproofingRoute: DraughtproofingRoute,
  HomeownersRoute: HomeownersRoute,
  InteriorDesignersRoute: InteriorDesignersRoute,
  ManagingAgentsRoute: ManagingAgentsRoute,
  SashWindowsRoute: SashWindowsRoute,
  SecondaryGlazingRoute: SecondaryGlazingRoute,
  VacuumGlazingRoute: VacuumGlazingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
